version: 2
updates:
  # Go
  - package-ecosystem: 'npm'
    directory: '/'
    open-pull-requests-limit: 5
    schedule:
      interval: 'monthly'
    groups:
      patch:
        update-types:
          - 'patch'

  # Github Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
